### PR TITLE
Pin Node version to 18.18.1

### PR DESCRIPTION
**Pull request by sylvansson**
This PR adds a [`.nvmrc`](https://github.com/nvm-sh/nvm) file and pins the Node version in existing configuration files to ensure that the version we use locally matches what is used in CircleCI and in production.

Moving forward, we'll have to make sure we update the Node version everywhere it's pinned.

### CODE REVIEW

**Review by martinbedouret — APPROVED** [review]

**Review by tomivm — APPROVED** [review]

**Review by RodriSanchez1 — COMMENTED** [review]
I think if we update the node version to 18 we need to update also the Cboard project (currently using node version 16). If not we can't run the both projects on the same machine.

**Comment by sylvansson** [comment]
@RodriSanchez1 I might be missing something but cboard-api should be running in its own Docker image, so I wouldn't expect that to be an issue.

**Comment by RodriSanchez1** [comment]
@sylvansson Yes, you are right. I was thinking when developing. For example when we  run the cboard-api will need to use node version 18 and for run the cboard will need to use the node version 16.  Sometimes we use both projects running at the same time. What do you think about this?

**Comment by sylvansson** [comment]
I did a quick test on my machine and it seems to work just fine. When you run `nvm use` it only changes the Node version for the current terminal. But I would encourage you to pull my branch and double check :-)

**Comment by RodriSanchez1** [comment]
@sylvansson I made a further research. The problem is on Windows 😞 .  Is not the same nvm package than the nvm linux/mac.
See: _When you do run nvm use x.x.x, the active version of node is automatically updated across all open console windows. It also persists between system reboots, so you only need to use nvm when you want to make a change._ from [nvm-windows](https://github.com/coreybutler/nvm-windows#bulb-whats-the-big-difference) . So, when I change the node version, it is changing for all the terminals opened :S. 

I'm thinking how we can solve this. Probably update the node version of Cboard, and merge both bumps together. 

Im Windows user LOL XD

**Review by RodriSanchez1 — APPROVED** [review]
@sylvansson I will update the cboard node version to 18 and merge both bumps!

**Comment by sylvansson** [comment]
@RodriSanchez1 Ok! I did a bit of research too and found [nvm-session](https://github.com/davfive/nvm-session), which might solve this for you.

**Pull request merged**
